sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "g9JiponrSmhvla7aXu37yU8rIPvpbZ9UOD9dJE3l5OcgI+0/a2oQ1eVp8aM0uLGpc8SLMRir/hvShYfjyxw6azjYsPwA13z32paseOTeqevWx8ml6+h8bWpAw+jyIr8SdJ78z9puBxIRpIJI3HupHg1L+OZu4In/hPNY5kzNS3BnJU26RiSD1YpAOkvF795HgpLB9PBMwQftYkmOHyf1e8AdM2mSHwwS2LAlzN9xHcQZSSjZmHpWeoqs4Ique4nE7m6futhEfe++12Khkga6TgiNKuaKnmKs9AHUvZPlrX5dZ62x4ak+xVIKdsdOS/m8s4qHDFCHPulxvqeHfoJ9V3TZNrq+lpazVyIgC3PWd0c/hIWJcK7PIEeuGtvLLXM4mC2SKxfhHfZRdlcVmAwDFIGSHbMAQjReoIyuZxyyGglFVeUgMqk91KcduasFwOqIVvRzxAf7kgX8me7bSGXh4EaIpUVU7f6MX38bTgk5mNnfDzcAp/qxvUdqTe6R9HXLeGVSY2WmtoGZOCfFsrg8EmtVsSxMF1bcCcct/mpLoHfIyTwTwiAFXbChFcxoIBx1VYNHuYfK4jTF/qo1hZJqpFTQDScZmir2RP7k/A5m2ujjzXAW7oy1sNAf1mfT9fWdEAutqqNmRzNJAImY6cz9YLfMKDNOSd/EiIIWws6xcgM="
  - secure: "I09sBrIwP+wD3jMufUEv1ZKxNPE2ehY6vUJlhq3x1yKkdKna6ZpAuZ46UbiWbOELuWx/CCoLui3VOSTlrj+ho907Y6+pipetz+s7dRYtX39KDGVEDJFkuqrkqcowUL5v2lCN4xVmDpV2FzCrIgUNKUMZZAixpjiSw4E9q7X7caFxUMLGh3ZVFK5AXwVdr9lTVK3MflwFhHQ44gPgoU3mMiNNEigBoCHfyl/A55vz0Aw0z/zEpicpjmXJQvPwHn0WKvopF402z8mmTjbQd8mw95IKmFcrEwr2O2As+ArY98VW5o7bMSPtFdj5eJySeMy/JRK+AHg+8lJrCJIH5VFZlI9zqCj0sb4KjkTertszaU4ByBbU7VsfmgiRdfEQ42KlIlUpYTqta1oGaLcl2XZzAYIHwCEooyEHlW9EokPWb93+OL71TQ4EIv3njLRL+QhOsDedfdd0c+YrryaG0nZJELZHaxGnkN6rBlL4pkigXYhElYfQ3/rb7Fhsrn+krxG9EsG8zJyf+t3nkcesv56vQuHC6Vee4la/5OAkeSSP52dmeX8SPanCPi+1OfAjBR80QTrZWzXEmwM0EtK9MFAuQGF2JIMbpKUDaVodjcDpDwZz78TAOJ0u5+uGknwMpceafHnuoKeXx3M9RMTSJvZNWros0HNyW5j5JNa2ePzKzvc="
  - secure: "TLENiRfXOY4jIJtD+BHk/zgjVn6rJd33j6X6JUrP7Lu8mF2dYT1+oiSHa5hZrBsuYz70kOWjjVH5g0KPSkQjAlyUOrlHLPIWxJxOGCr30QvyjsYzhjd7WfakX/kD2+D5ALS9sEd24KgpERH4fIAJKDjDLfmyXeP4E3PU5WPTj8Gov8wTcke5L1J0z7vCMjeGo0h+5HslOmfNtPllPqREoPEo9D7zh2/oEd+SQQyUqS2cXwf83esaSzGmRb7TcyqCpPk6TgR0IYsWTgsMh6bft5QkTErWVz742VrK2hTbDlEbkUOsiCHqNiSguHJ9Jx6aaa02y42XhsoMx5dcXSmO9wUjRsg020qDDvdvHVuUmaslehXBBB8ZhsDU74FHJQdodKjkD6RzmfDL/s4hil39hqmn8JXwuanaMSsHh6/0yeHOUFQfJhBZy7kFoGjAwbpY1sLPb2UXAAv9lmanFZP/wuc+/KjzQwnsj5eMnMZuHqQcZSKrFNyM/qbopDDYQudd7ufjEiOD0fYpOdRA7o90slufcIcvacXbQno5DRS0PGdkuVrtz5yzkMlNlQkuXUq6R5cUL474GsYcQ2YVq4t1wVdAKyT/aWhg3UEUTMCQajNvhGpsQbH60/GrZp7tLqIiGmAyTbzSpejCZi7FU+++ZL4Edd/WZwxEey1PdpM2egk="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
